Repository TeachMe-CloudUS/teachme-ratings-service, pull requests merged in 2024-11, with the labels that each got.

#2 config: Configuración SpringBoot, Maven, MongoDB#1
  microservicio-valoraciones/.gitattributes
  microservicio-valoraciones/.gitignore
  microservicio-valoraciones/.mvn/wrapper/maven-wrapper.properties
  microservicio-valoraciones/compose.yaml
  microservicio-valoraciones/mvnw
  microservicio-valoraciones/mvnw.cmd
  microservicio-valoraciones/pom.xml
  microservicio-valoraciones/src/main/java/teachme5/microservicio_valoraciones/MicroservicioValoracionesApplication.java
  microservicio-valoraciones/src/main/resources/application.properties
  microservicio-valoraciones/src/test/java/teachme5/microservicio_valoraciones/MicroservicioValoracionesApplicationTests.java
Labels: config

#4 conf: Actualización de la configuración #1
  .github/workflows/blank.yml
  .gitignore
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  .vscode/settings.json
  LICENSE
  microservicio-valoraciones/.gitattributes
  microservicio-valoraciones/.gitignore
  microservicio-valoraciones/compose.yaml
  microservicio-valoraciones/mvnw
  microservicio-valoraciones/mvnw.cmd
  microservicio-valoraciones/pom.xml
  microservicio-valoraciones/src/main/java/teachme5/microservicio_valoraciones/MicroservicioValoracionesApplication.java
  microservicio-valoraciones/src/main/resources/application.properties
  microservicio-valoraciones/src/test/java/teachme5/microservicio_valoraciones/MicroservicioValoracionesApplicationTests.java
  mvnw
  mvnw.cmd
  pom.xml
  src/main/java/com/mongodb/starter/ApplicationStarter.java
  src/main/java/com/mongodb/starter/MongoClientConfig.java
  src/main/resources/application.properties
  src/main/resources/logback-spring.xml
Labels: config

#16 feat: método findAllRatingsByCourse y edición de los endpoints #3
  src/main/java/com/mongodb/starter/rating/RatingController.java
  src/main/java/com/mongodb/starter/rating/RatingRepository.java
  src/main/java/com/mongodb/starter/rating/RatingService.java
Labels: feat, backend

#26 Fix: Variables de entorno asignadas en la uri
  src/main/resources/application.properties
Labels: fix
